apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-5-vol3
spec:
  capacity:
    storage: 2.5Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data1/vol3
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - es-5