apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.ingest.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "elasticsearch.ingest.fullname" . }}
{{- if .Values.ingest.serviceAnnotations }}
  annotations:
{{ toYaml .Values.ingest.serviceAnnotations | indent 4 }}
{{- end }}

spec:
  ports:
    - name: http
      port: 9201
      targetPort: http
  selector:
    app: {{ template "elasticsearch.name" . }}
    component: "{{ .Values.ingest.name }}"
    release: {{ .Release.Name }}
  type: {{ .Values.ingest.serviceType }}
{{- if .Values.ingest.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.ingest.loadBalancerIP }}"
{{- end }}
  {{if .Values.ingest.loadBalancerSourceRanges}}
  loadBalancerSourceRanges:
    {{range $rangeList := .Values.ingest.loadBalancerSourceRanges}}
    - {{ $rangeList }}
    {{end}}
  {{end}}